services:
  ss-db:
    build: ./db
    container_name: 'ss_db'
    ports:
      - 5432:5432
    environment:
        POSTGRES_MULTIPLE_DATABASES: keycloak,users,documents,collaborations
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ss-net
    volumes:
      - ss-db:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: ss_keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://ss_db:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - ss-db
    ports:
      - 8080:8080
    networks:
      - ss-net
  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ss-minio:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: curl --fail http://127.0.0.1:9000/minio/health/live || exit 1
    networks:
      - ss-net
networks:
  ss-net:
    driver: bridge
volumes:
  ss-db:
  ss-minio:
