spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/collaboration
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8000