app:
  secretKey: QHt8RSvlB4Tq2ENg
minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: document
management:
  server:
    port: 8102
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      accept-single-value-as-array: true
  cloud:
    openfeign:
      client:
        config:
          emailService.url: http://localhost:8000
  datasource:
    url: jdbc:postgresql://localhost:5432/files
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${zitadel.baseUrl}/oauth/v2/introspect
          client-id: 315804175931867140
          client-secret: cbtdOmQ7U5aY6eAYjYX3MJ5Zz8zNm87JXP0Tg2llX6YWPj21TMqiOfe3ypFrC2Po
server:
  port: 8002
zitadel:
  baseUrl: http://localhost:8080