management:
  server:
    port: 8103
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/idp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${zitadel.baseUrl}
server:
  port: 8003
zitadel:
  baseUrl: http://localhost:8080
