management:
  server:
    port: 8100
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/syncscribe
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${zitadel.baseUrl}/oauth/v2/introspect
          client-id: 315830414038073348
          client-secret: AyQKO6d2DlT8kwMlVpDgLBnafotchcycP4wbW7IHl7aXk1BMipUKiUh4sFtkKjRz
server:
  port: 8000
zitadel:
  baseUrl: http://localhost:8080
