management:
  server:
    port: 8103
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/emails
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangna1204.dev@gmail.com
    password: rlbf aivp vfzt isup
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${zitadel.baseUrl}/oauth/v2/introspect
          client-id: 315804228780097540
          client-secret: 5lthTy35k1qAXbCFMq1bd13ByqbJod5AUhpCQFsOrtvK4gjMeoI3kPjhmHeSojSr
  thymeleaf:
    cache: true
server:
  port: 8003
zitadel:
  baseUrl: http://localhost:8080
    
