management:
  server:
    port: 8102
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/emails
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangna1204.dev@gmail.com
    password: uysc nxuk zqwm ggic
    sender: hoangna1204.dev@gmail.com
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${zitadel.baseUrl}/oauth/v2/introspect
          client-id: 315691793633050628
          client-secret: 64kxK5ShaLkmFtvrF1POklh7w4ee0ZsKzYceDteG2koBhM1e5v6ghdgWAgjJhbSK
  thymeleaf:
    cache: true
server:
  port: 8002
zitadel:
  baseUrl: http://localhost:8080
    
